/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI-PC
 */
public class RegisterFormOwner extends javax.swing.JFrame {

    BufferedReader msgFromServer;
    DataOutputStream msgToServer;
    String ownerData;

    public RegisterFormOwner() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            //buat penerima dan pengirim dari socket
            msgFromServer = new BufferedReader(new InputStreamReader(LoginForm.s.getInputStream()));
            msgToServer = new DataOutputStream(LoginForm.s.getOutputStream());
        } catch (Exception ex) {
            System.out.println("FormRegisterRestaurant Constructor1, Error: " + ex.getMessage());
        }
    }

    public RegisterFormOwner(String data) {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            //buat penerima dan pengirim dari socket
            msgFromServer = new BufferedReader(new InputStreamReader(LoginForm.s.getInputStream()));
            msgToServer = new DataOutputStream(LoginForm.s.getOutputStream());

            String[] messages = null;
            // data = <nama> <username> <password> <role>
            messages = data.split(";-;");

            txtName.setText(messages[0]);
            txtUsername.setText(messages[1]);

        } catch (Exception ex) {
            System.out.println("FormRegisterRestaurant Constructor2, Error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResgisterRest = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtRePassword = new javax.swing.JTextField();
        btnRegisterRestaurant = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        lblBackToLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRePassword = new javax.swing.JLabel();
        lblBackToLogin1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(460, 580));
        setSize(new java.awt.Dimension(460, 550));
        getContentPane().setLayout(null);

        lblResgisterRest.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblResgisterRest.setForeground(new java.awt.Color(255, 255, 255));
        lblResgisterRest.setText("Register Owner Data");
        getContentPane().add(lblResgisterRest);
        lblResgisterRest.setBounds(100, 30, 250, 32);

        txtName.setBackground(new java.awt.Color(242, 242, 242));
        txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(50, 120, 350, 28);

        txtPassword.setBackground(new java.awt.Color(242, 242, 242));
        txtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtPassword);
        txtPassword.setBounds(50, 280, 350, 28);

        txtRePassword.setBackground(new java.awt.Color(242, 242, 242));
        txtRePassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtRePassword);
        txtRePassword.setBounds(50, 360, 350, 28);

        btnRegisterRestaurant.setBackground(new java.awt.Color(244, 203, 14));
        btnRegisterRestaurant.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegisterRestaurant.setForeground(new java.awt.Color(2, 26, 74));
        btnRegisterRestaurant.setText("NEXT");
        btnRegisterRestaurant.setBorderPainted(false);
        btnRegisterRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterRestaurantActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegisterRestaurant);
        btnRegisterRestaurant.setBounds(170, 420, 130, 38);

        txtUsername.setBackground(new java.awt.Color(242, 242, 242));
        txtUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtUsername);
        txtUsername.setBounds(50, 200, 350, 28);

        lblBackToLogin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblBackToLogin.setText("Already have an account?");
        lblBackToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBackToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackToLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lblBackToLogin);
        lblBackToLogin.setBounds(120, 480, 170, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 90, 51, 24);

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(50, 170, 90, 24);

        lblPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(50, 250, 110, 24);

        lblRePassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRePassword.setForeground(new java.awt.Color(255, 255, 255));
        lblRePassword.setText("Re-type Password");
        getContentPane().add(lblRePassword);
        lblRePassword.setBounds(50, 330, 160, 24);

        lblBackToLogin1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBackToLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblBackToLogin1.setText("Login");
        lblBackToLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBackToLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackToLogin1MouseClicked(evt);
            }
        });
        getContentPane().add(lblBackToLogin1);
        lblBackToLogin1.setBounds(290, 480, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auth/images/backg.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 470, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterRestaurantActionPerformed
        try {
            if (txtPassword.getText().equals(txtRePassword.getText())) {
                // kirim Request Data (REGISTER <username> <password> <role>)
                msgToServer.writeBytes("CHECK_SAME_USERNAME//" + txtUsername.getText() + "\n");

                String result;
                result = msgFromServer.readLine();

                String[] messages = null;
                messages = result.split(";-;");

                String cmd = "";
                cmd = messages[0];

                // kalau ketemu username sama
                if (cmd.equals("TRUE")) {
                    JOptionPane.showMessageDialog(this, "Sorry " + txtName.getText() + ", Your username has been taken.");
                }// kalau tidak ketemu username yang sama
                else if (cmd.equals("FALSE")) {
                    ownerData = txtName.getText() + ";-;" + txtUsername.getText() + ";-;" + txtPassword.getText() + ";-;restaurant" + "\n";
                    new RegisterFormRestaurant(ownerData).setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Your passwords are not the same!!");
            }
        } catch (Exception e) {
            System.out.println("RegisterFormOwner btnRegister, Error; " + e);
            Logger.getLogger(RegisterFormOwner.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnRegisterRestaurantActionPerformed

    private void lblBackToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackToLoginMouseClicked
        new LoginForm(LoginForm.s).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackToLoginMouseClicked

    private void lblBackToLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackToLogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBackToLogin1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegisterFormOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegisterFormOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegisterFormOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegisterFormOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegisterFormOwner().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterRestaurant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackToLogin;
    private javax.swing.JLabel lblBackToLogin1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRePassword;
    private javax.swing.JLabel lblResgisterRest;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
